// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to
// build this package and to use Swift Package Manager with this Flutter plugin.

import PackageDescription

let package = Package(
    name: "zmedia_player",
    platforms: [
        // iOS 13 minimum: the plugin uses Swift concurrency (async/await), and
        // Flutter 3.44+ no longer supports iOS 12.
        .iOS("13.0")
    ],
    products: [
        // The library product name follows Flutter's SPM convention
        // (package name with underscores replaced by hyphens).
        .library(name: "zmedia-player", targets: ["zmedia_player"])
    ],
    dependencies: [
        // Flutter 3.44+ exposes the engine as the FlutterFramework Swift package,
        // generated by the Flutter build alongside the plugin packages.
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        .target(
            name: "zmedia_player",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ]
            // Pure-Swift plugin: sources under Sources/zmedia_player/, no C/ObjC
            // headers and no external (non-Flutter) dependencies.
        )
    ]
)
