name: zmedia_player
description: A comprehensive Flutter media player package with advanced features for video and audio playback.
version: 0.2.5
homepage: https://github.com/zionmedianetwork/zmedia_player
repository: https://github.com/zionmedianetwork/zmedia_player

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  path: ^1.8.0
  http: ^1.1.0
  fluentui_system_icons: ^1.1.273
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.zionmedianetwork.zmedia_player
        pluginClass: ZMediaPlayerPlugin
      ios:
        pluginClass: ZMediaPlayerPlugin
