import 'dart:math';

import 'media_item.dart';

/// Represents a playlist of media items
class Playlist {
  /// Unique identifier for the playlist
  final String id;

  /// Display name of the playlist
  final String title;

  /// List of media items in the playlist
  final List<MediaItem> items;

  /// Current playing index
  final int currentIndex;

  /// Playback mode for the playlist
  final PlaybackMode mode;

  /// Whether the playlist should repeat
  final MediaRepeatMode repeatMode;

  /// Additional metadata
  final Map<String, dynamic>? metadata;

  /// Precomputed shuffled traversal order (a permutation of item indices),
  /// used when [mode] is [PlaybackMode.shuffle]. Generated by [copyWith] when
  /// the playlist enters shuffle mode; null for sequential playback.
  final List<int>? shuffleOrder;

  const Playlist({
    required this.id,
    required this.title,
    required this.items,
    this.currentIndex = 0,
    this.mode = PlaybackMode.sequential,
    this.repeatMode = MediaRepeatMode.none,
    this.metadata,
    this.shuffleOrder,
  });

  /// Builds a shuffled permutation of [0, length) with [startAt] kept first
  /// (so the current item stays current) and the remainder Fisher-Yates shuffled.
  static List<int> _buildShuffleOrder(int length, int startAt) {
    if (length <= 0) return const [];
    final rng = Random();
    final rest = <int>[
      for (var i = 0; i < length; i++)
        if (i != startAt) i
    ];
    for (var i = rest.length - 1; i > 0; i--) {
      final j = rng.nextInt(i + 1);
      final tmp = rest[i];
      rest[i] = rest[j];
      rest[j] = tmp;
    }
    if (startAt >= 0 && startAt < length) return [startAt, ...rest];
    return rest;
  }

  /// Creates a copy of this playlist with updated values
  Playlist copyWith({
    String? id,
    String? title,
    List<MediaItem>? items,
    int? currentIndex,
    PlaybackMode? mode,
    MediaRepeatMode? repeatMode,
    Map<String, dynamic>? metadata,
    List<int>? shuffleOrder,
  }) {
    final resolvedMode = mode ?? this.mode;
    final resolvedItems = items ?? this.items;
    final resolvedIndex = currentIndex ?? this.currentIndex;

    // Maintain a shuffled traversal order while in shuffle mode: reuse an
    // existing valid order, otherwise (re)generate one. Clear it for sequential.
    List<int>? resolvedShuffle;
    if (resolvedMode == PlaybackMode.shuffle) {
      final candidate = shuffleOrder ?? this.shuffleOrder;
      resolvedShuffle =
          (candidate != null && candidate.length == resolvedItems.length)
              ? candidate
              : _buildShuffleOrder(resolvedItems.length, resolvedIndex);
    }

    return Playlist(
      id: id ?? this.id,
      title: title ?? this.title,
      items: resolvedItems,
      currentIndex: resolvedIndex,
      mode: resolvedMode,
      repeatMode: repeatMode ?? this.repeatMode,
      metadata: metadata ?? this.metadata,
      shuffleOrder: resolvedShuffle,
    );
  }

  /// Current media item being played
  MediaItem? get currentItem {
    if (currentIndex >= 0 && currentIndex < items.length) {
      return items[currentIndex];
    }
    return null;
  }

  /// Whether there is a next item available
  bool get hasNext {
    switch (repeatMode) {
      case MediaRepeatMode.all:
        return items.isNotEmpty;
      case MediaRepeatMode.single:
        return true;
      case MediaRepeatMode.none:
        return currentIndex < items.length - 1;
    }
  }

  /// Whether there is a previous item available
  bool get hasPrevious {
    switch (repeatMode) {
      case MediaRepeatMode.all:
        return items.isNotEmpty;
      case MediaRepeatMode.single:
        return true;
      case MediaRepeatMode.none:
        return currentIndex > 0;
    }
  }

  /// Get the next index based on current playback mode
  int? get nextIndex {
    if (items.isEmpty) return null;

    switch (mode) {
      case PlaybackMode.sequential:
        return _getNextSequentialIndex();
      case PlaybackMode.shuffle:
        return _getNextShuffleIndex();
    }
  }

  /// Get the previous index based on current playback mode
  int? get previousIndex {
    if (items.isEmpty) return null;

    switch (mode) {
      case PlaybackMode.sequential:
        return _getPreviousSequentialIndex();
      case PlaybackMode.shuffle:
        return _getPreviousShuffleIndex();
    }
  }

  int? _getNextSequentialIndex() {
    switch (repeatMode) {
      case MediaRepeatMode.single:
        return currentIndex;
      case MediaRepeatMode.all:
        return (currentIndex + 1) % items.length;
      case MediaRepeatMode.none:
        return currentIndex < items.length - 1 ? currentIndex + 1 : null;
    }
  }

  int? _getPreviousSequentialIndex() {
    switch (repeatMode) {
      case MediaRepeatMode.single:
        return currentIndex;
      case MediaRepeatMode.all:
        return currentIndex > 0 ? currentIndex - 1 : items.length - 1;
      case MediaRepeatMode.none:
        return currentIndex > 0 ? currentIndex - 1 : null;
    }
  }

  int? _getNextShuffleIndex() {
    if (items.isEmpty) return null;
    if (repeatMode == MediaRepeatMode.single) return currentIndex;

    final order = _effectiveShuffleOrder;
    final pos = order.indexOf(currentIndex);
    final nextPos = pos + 1;
    if (nextPos < order.length) return order[nextPos];
    // Reached the end of the shuffled order.
    return repeatMode == MediaRepeatMode.all ? order.first : null;
  }

  /// The shuffle order to traverse, falling back to identity order if none was
  /// generated (e.g. a directly-constructed shuffle playlist not yet copied).
  List<int> get _effectiveShuffleOrder {
    final order = shuffleOrder;
    if (order != null && order.length == items.length) return order;
    return List<int>.generate(items.length, (i) => i);
  }

  int? _getPreviousShuffleIndex() {
    if (items.isEmpty) return null;
    if (repeatMode == MediaRepeatMode.single) return currentIndex;

    final order = _effectiveShuffleOrder;
    final pos = order.indexOf(currentIndex);
    final prevPos = pos - 1;
    if (prevPos >= 0) return order[prevPos];
    // Reached the start of the shuffled order.
    return repeatMode == MediaRepeatMode.all ? order.last : null;
  }

  /// Add an item to the playlist
  Playlist addItem(MediaItem item) {
    return copyWith(items: [...items, item]);
  }

  /// Insert an item at a specific index
  Playlist insertItem(int index, MediaItem item) {
    final newItems = List<MediaItem>.from(items);
    newItems.insert(index.clamp(0, items.length), item);
    return copyWith(items: newItems);
  }

  /// Remove an item at a specific index
  Playlist removeItemAt(int index) {
    if (index < 0 || index >= items.length) return this;

    final newItems = List<MediaItem>.from(items);
    newItems.removeAt(index);

    int newCurrentIndex = currentIndex;
    if (index < currentIndex) {
      newCurrentIndex = currentIndex - 1;
    } else if (index == currentIndex && currentIndex >= newItems.length) {
      newCurrentIndex = newItems.isEmpty ? 0 : newItems.length - 1;
    }

    return copyWith(
      items: newItems,
      currentIndex: newCurrentIndex,
    );
  }

  /// Move to a specific index
  Playlist moveToIndex(int index) {
    if (index < 0 || index >= items.length) return this;
    return copyWith(currentIndex: index);
  }

  /// Total duration of all items in the playlist
  Duration get totalDuration {
    return items.fold(Duration.zero, (total, item) {
      return total + (item.duration ?? Duration.zero);
    });
  }

  /// Whether the playlist is empty
  bool get isEmpty => items.isEmpty;

  /// Number of items in the playlist
  int get length => items.length;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is Playlist && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() {
    return 'Playlist(id: $id, title: $title, items: ${items.length}, currentIndex: $currentIndex)';
  }
}

/// Playback mode for playlists
enum PlaybackMode {
  /// Play items in sequential order
  sequential,

  /// Play items in random order
  shuffle,
}

/// Repeat mode for playlists
enum MediaRepeatMode {
  /// No repeat
  none,

  /// Repeat current item
  single,

  /// Repeat entire playlist
  all,
}
