// Regression tests for the real shuffle order fix in Playlist.
//
// Before the fix, nextIndex in shuffle mode returned (currentIndex+1)%length
// — a sequential stub. After the fix, copyWith(mode: PlaybackMode.shuffle)
// generates a Fisher-Yates permutation stored in shuffleOrder, and
// nextIndex/previousIndex traverse it instead of computing sequentially.

import 'package:flutter_test/flutter_test.dart';
import 'package:zmedia_player/zmedia_player.dart';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

List<MediaItem> _makeItems(int count) => List.generate(
      count,
      (i) => MediaItem(
        id: 'item-$i',
        title: 'Track $i',
        url: 'https://example.com/track$i.mp4',
      ),
    );

/// Returns all indices reachable from [startIndex] by calling nextIndex until
/// null is returned, updating currentIndex via copyWith on each step.
/// Returns the traversal order (not including the initial startIndex itself —
/// the list represents the NEXT targets visited, matching shuffleOrder[1..n]).
List<int> _traverseNext(Playlist playlist) {
  final visited = <int>[];
  var current = playlist;
  while (true) {
    final next = current.nextIndex;
    if (next == null) break;
    visited.add(next);
    current = current.copyWith(currentIndex: next);
  }
  return visited;
}

/// Returns all indices reachable going backwards from [startIndex] via
/// previousIndex until null is returned.
List<int> _traversePrev(Playlist playlist) {
  final visited = <int>[];
  var current = playlist;
  while (true) {
    final prev = current.previousIndex;
    if (prev == null) break;
    visited.add(prev);
    current = current.copyWith(currentIndex: prev);
  }
  return visited;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  group('Playlist.shuffleOrder — generated by copyWith(mode: shuffle)', () {
    test('copyWith to shuffle produces non-null shuffleOrder', () {
      final items = _makeItems(5);
      final seq = Playlist(
        id: 'pl-shuffle-1',
        title: 'Shuffle Test',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
      );

      final shuffled = seq.copyWith(mode: PlaybackMode.shuffle);

      expect(
        shuffled.shuffleOrder,
        isNotNull,
        reason: 'copyWith(mode: shuffle) must generate a non-null shuffleOrder',
      );
    });

    test('shuffleOrder has the same length as items', () {
      final items = _makeItems(8);
      final shuffled = Playlist(
        id: 'pl-shuffle-2',
        title: 'Shuffle Test',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
      ).copyWith(mode: PlaybackMode.shuffle);

      expect(
        shuffled.shuffleOrder!.length,
        items.length,
        reason: 'shuffleOrder.length must equal items.length',
      );
    });

    test('shuffleOrder is a valid permutation of 0..n-1', () {
      final items = _makeItems(8);
      final shuffled = Playlist(
        id: 'pl-shuffle-perm',
        title: 'Permutation Test',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
      ).copyWith(mode: PlaybackMode.shuffle);

      final order = shuffled.shuffleOrder!;
      final sorted = List<int>.from(order)..sort();

      expect(
        sorted,
        List<int>.generate(items.length, (i) => i),
        reason:
            'shuffleOrder must be a permutation of every index 0..n-1 exactly once',
      );
    });

    test('shuffleOrder starts with currentIndex (current item stays current)',
        () {
      final items = _makeItems(6);
      const startIndex = 3;
      final shuffled = Playlist(
        id: 'pl-shuffle-start',
        title: 'Start Index Test',
        items: items,
        currentIndex: startIndex,
        mode: PlaybackMode.sequential,
      ).copyWith(mode: PlaybackMode.shuffle);

      expect(
        shuffled.shuffleOrder!.first,
        startIndex,
        reason:
            'shuffleOrder[0] must be currentIndex so the current item does not jump',
      );
    });

    test(
        'copyWith(mode: sequential) clears shuffleOrder back to null and nextIndex is sequential',
        () {
      final items = _makeItems(5);
      final shuffled = Playlist(
        id: 'pl-shuffle-clear',
        title: 'Clear Test',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
      ).copyWith(mode: PlaybackMode.shuffle);

      // Sanity: shuffle order is set.
      expect(shuffled.shuffleOrder, isNotNull);

      final sequential = shuffled.copyWith(mode: PlaybackMode.sequential);

      expect(
        sequential.shuffleOrder,
        isNull,
        reason: 'Switching back to sequential must clear shuffleOrder to null',
      );

      // nextIndex follows normal sequential logic again.
      expect(
        sequential.nextIndex,
        1,
        reason: 'After clearing shuffle, nextIndex must return currentIndex+1',
      );
    });

    test(
        'traversal with shuffle+RepeatMode.none visits every item exactly once then returns null',
        () {
      // Use 8 items for a meaningful test — small enough to be deterministic
      // in each run but large enough to catch sequential ordering with high
      // probability (probability that shuffled == sequential is 1/8! < 1e-4).
      final items = _makeItems(8);
      final shuffled = Playlist(
        id: 'pl-traverse-none',
        title: 'Full Traversal',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
        repeatMode: RepeatMode.none,
      ).copyWith(mode: PlaybackMode.shuffle);

      final order = shuffled.shuffleOrder!;

      // Traverse all nextIndex values starting at shuffleOrder[0] = currentIndex.
      final visited = _traverseNext(shuffled);

      // Must have visited exactly n-1 items after the start item.
      expect(
        visited.length,
        items.length - 1,
        reason:
            'With RepeatMode.none traversal must visit every item exactly once '
            'then return null',
      );

      // The visited sequence must equal shuffleOrder[1..] exactly.
      expect(
        visited,
        order.sublist(1),
        reason:
            'nextIndex traversal must follow the generated shuffleOrder, not sequential order',
      );

      // Confirm the traversal is NOT plain sequential (0,1,2,3,...) for 8 items.
      // The chance of a random permutation matching identity from index 1 is
      // negligible; if it somehow does, we accept it — but we assert the ORDER
      // matches shuffleOrder, which is the stronger guarantee.
      final identityFromOne =
          List<int>.generate(items.length - 1, (i) => i + 1);
      // We only warn, not hard-fail, because a random permutation could match
      // identity. The important assertion is that traversal follows shuffleOrder.
      if (visited == identityFromOne) {
        // This is extremely unlikely but valid. The permutation happened to be
        // the identity. The test already proved traversal == shuffleOrder, so
        // the fix is still covered.
      }
    });

    test(
        'traversal with shuffle+RepeatMode.none traversal order != sequential for 8 items (statistical guard)',
        () {
      // Run 5 independent shuffled playlists and assert that AT LEAST ONE
      // produces a non-sequential order. The probability all five are sequential
      // is (1/8!)^5 which is astronomically small.
      final items = _makeItems(8);
      final identityFrom1 = List<int>.generate(items.length - 1, (i) => i + 1);

      bool foundNonSequential = false;
      for (var attempt = 0; attempt < 5; attempt++) {
        final shuffled = Playlist(
          id: 'pl-stat-$attempt',
          title: 'Stat Test',
          items: items,
          currentIndex: 0,
          mode: PlaybackMode.sequential,
          repeatMode: RepeatMode.none,
        ).copyWith(mode: PlaybackMode.shuffle);

        final visited = _traverseNext(shuffled);
        if (visited != identityFrom1) {
          foundNonSequential = true;
          break;
        }
      }

      expect(
        foundNonSequential,
        isTrue,
        reason:
            'Shuffle must produce a non-sequential order (stub bug was returning '
            'sequential (currentIndex+1)%length)',
      );
    });

    test(
        'shuffle+RepeatMode.all: after the last shuffled item, nextIndex wraps to shuffleOrder.first',
        () {
      final items = _makeItems(5);
      final shuffled = Playlist(
        id: 'pl-shuffle-all-wrap',
        title: 'Wrap Test',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
        repeatMode: RepeatMode.all,
      ).copyWith(mode: PlaybackMode.shuffle);

      final order = shuffled.shuffleOrder!;
      final lastInOrder = order.last;

      // Position at the last item in the shuffle order.
      final atLast = shuffled.copyWith(currentIndex: lastInOrder);
      expect(
        atLast.nextIndex,
        order.first,
        reason:
            'RepeatMode.all must wrap nextIndex from the last shuffled item back to shuffleOrder.first',
      );
    });

    test('shuffle+RepeatMode.single: nextIndex returns currentIndex', () {
      final items = _makeItems(5);
      final shuffled = Playlist(
        id: 'pl-shuffle-single',
        title: 'Single Repeat Shuffle',
        items: items,
        currentIndex: 2,
        mode: PlaybackMode.sequential,
        repeatMode: RepeatMode.single,
      ).copyWith(mode: PlaybackMode.shuffle);

      expect(
        shuffled.nextIndex,
        2,
        reason:
            'RepeatMode.single must always return currentIndex regardless of shuffle mode',
      );
    });

    test(
        'previousIndex follows shuffleOrder in reverse: visiting via previousIndex traces shuffleOrder backwards',
        () {
      final items = _makeItems(6);
      // Build the shuffled playlist starting at index 0.
      final shuffled = Playlist(
        id: 'pl-shuffle-prev',
        title: 'Prev Traversal',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
        repeatMode: RepeatMode.none,
      ).copyWith(mode: PlaybackMode.shuffle);

      final order = shuffled.shuffleOrder!;

      // Position at the LAST item in the shuffle order — from there going
      // backwards we should traverse order in reverse.
      final atLast = shuffled.copyWith(currentIndex: order.last);
      final visited = _traversePrev(atLast);

      // We expect to visit order[n-2], order[n-3], ..., order[0].
      final expected = order.reversed.skip(1).toList();

      expect(
        visited,
        expected,
        reason:
            'previousIndex traversal must follow shuffleOrder in reverse order',
      );
    });

    test(
        'shuffle+RepeatMode.all: previousIndex at shuffleOrder.first wraps to shuffleOrder.last',
        () {
      final items = _makeItems(5);
      final shuffled = Playlist(
        id: 'pl-shuffle-prev-wrap',
        title: 'Prev Wrap',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
        repeatMode: RepeatMode.all,
      ).copyWith(mode: PlaybackMode.shuffle);

      final order = shuffled.shuffleOrder!;
      final firstInOrder = order.first;

      final atFirst = shuffled.copyWith(currentIndex: firstInOrder);
      expect(
        atFirst.previousIndex,
        order.last,
        reason:
            'RepeatMode.all must wrap previousIndex from shuffleOrder.first to shuffleOrder.last',
      );
    });

    test('nextIndex is stable (same value returned on repeated calls)', () {
      final items = _makeItems(7);
      final shuffled = Playlist(
        id: 'pl-shuffle-stable',
        title: 'Stability Test',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
        repeatMode: RepeatMode.none,
      ).copyWith(mode: PlaybackMode.shuffle);

      // Call nextIndex three times on the same immutable instance.
      final first = shuffled.nextIndex;
      final second = shuffled.nextIndex;
      final third = shuffled.nextIndex;

      expect(
        first,
        isNotNull,
        reason: 'nextIndex must not be null at the start of a 7-item playlist',
      );
      expect(
        second,
        first,
        reason:
            'nextIndex must be stable — driven by shuffleOrder, not re-randomized',
      );
      expect(
        third,
        first,
        reason: 'nextIndex must be stable across repeated calls',
      );
    });

    test('reusing existing valid shuffleOrder when copyWith preserves it', () {
      final items = _makeItems(4);
      final original = Playlist(
        id: 'pl-reuse',
        title: 'Reuse Test',
        items: items,
        currentIndex: 0,
        mode: PlaybackMode.sequential,
      ).copyWith(mode: PlaybackMode.shuffle);

      final order = original.shuffleOrder!;

      // copyWith with no mode change and same items must reuse the order.
      final advanced = original.copyWith(currentIndex: order[1]);

      expect(
        advanced.shuffleOrder,
        order,
        reason:
            'copyWith on an already-shuffled playlist must reuse the existing valid shuffleOrder',
      );
    });
  });
}
